-- ==============================================================================
-- KRUSHI QUICK-START SUPABASE SETUP
-- Project: hccppqykmjfcpjmhntks.supabase.co
-- Run this in your Supabase Dashboard: SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. Create the telemetry table
CREATE TABLE IF NOT EXISTS public.esp32_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL DEFAULT 'AGRITRACE-001',
    shipment_id TEXT DEFAULT '04beaccb-7c55-44ab-aa84-2a3f338dcf1c',
    sequence BIGINT DEFAULT 1,
    temperature NUMERIC(5, 2) NOT NULL,
    humidity NUMERIC(5, 2) NOT NULL,
    gas_ethylene NUMERIC(6, 2) NOT NULL,
    latitude NUMERIC(9, 6) DEFAULT 19.0760,
    longitude NUMERIC(9, 6) DEFAULT 72.9982,
    battery NUMERIC(4, 1) DEFAULT 95.0,
    solar_power_mw NUMERIC(6, 1) DEFAULT 320.0,
    network_state TEXT DEFAULT 'online',
    sync_state TEXT DEFAULT 'live',
    integrity_status TEXT DEFAULT 'verified',
    synced_to_local BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.esp32_telemetry ENABLE ROW LEVEL SECURITY;

-- 3. Allow anonymous insert and select so your ESP32 anon key can write & read directly
DROP POLICY IF EXISTS "Allow anon insert from ESP32" ON public.esp32_telemetry;
CREATE POLICY "Allow anon insert from ESP32"
ON public.esp32_telemetry
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon select" ON public.esp32_telemetry;
CREATE POLICY "Allow anon select"
ON public.esp32_telemetry
FOR SELECT
TO anon, authenticated
USING (true);

-- 4. Grant table access to anon and authenticated roles
GRANT ALL ON public.esp32_telemetry TO anon;
GRANT ALL ON public.esp32_telemetry TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
