-- ==============================================================================
-- KRUSHI SUPABASE HARDENED ROW LEVEL SECURITY (RLS) SPECIFICATION
-- SIH Problem Statement 26232: Cold-Chain Integrity & Traceability
--
-- Security Goal:
-- Eliminate direct unauthenticated write access from IoT devices via public anon keys.
-- Enforce that all telemetry flows through the trusted Krushi Ingestion Gateway API.
-- ==============================================================================

-- 1. Ensure table structure
CREATE TABLE IF NOT EXISTS public.esp32_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL,
    shipment_id TEXT,
    sequence BIGINT NOT NULL,
    temperature NUMERIC(5, 2) NOT NULL,
    humidity NUMERIC(5, 2) NOT NULL,
    gas_ethylene NUMERIC(6, 2) NOT NULL,
    latitude NUMERIC(9, 6) DEFAULT 19.0760,
    longitude NUMERIC(9, 6) DEFAULT 72.9982,
    battery NUMERIC(4, 1) DEFAULT 94.5,
    solar_power_mw NUMERIC(6, 1) DEFAULT 320.0,
    network_state TEXT DEFAULT 'online',
    previous_hash TEXT,
    record_hash TEXT,
    signature TEXT,
    integrity_status TEXT DEFAULT 'pending',
    synced_to_local BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Performance indexes
CREATE INDEX IF NOT EXISTS idx_telem_device_seq ON public.esp32_telemetry(device_id, sequence);
CREATE INDEX IF NOT EXISTS idx_telem_shipment ON public.esp32_telemetry(shipment_id, created_at);
CREATE INDEX IF NOT EXISTS idx_telem_sync ON public.esp32_telemetry(synced_to_local, created_at);

-- 3. LOCK DOWN: Enable Row Level Security (RLS)
ALTER TABLE public.esp32_telemetry ENABLE ROW LEVEL SECURITY;

-- 4. DROP ALL INSECURE OPEN POLICIES
DROP POLICY IF EXISTS "Allow anon insert from ESP32" ON public.esp32_telemetry;
DROP POLICY IF EXISTS "Allow anon select and update for backend sync" ON public.esp32_telemetry;
DROP POLICY IF EXISTS "Public can view telemetry" ON public.esp32_telemetry;

-- 5. REVOKE DANGEROUS PERMISSIONS FROM ANON & AUTHENTICATED WEB ROLES
REVOKE INSERT, UPDATE, DELETE ON public.esp32_telemetry FROM anon;
REVOKE INSERT, UPDATE, DELETE ON public.esp32_telemetry FROM authenticated;

-- 6. GRANT READ PRIVILEGES FOR PUBLIC DASHBOARD / READ-ONLY CONSUMER VERIFICATION
CREATE POLICY "Allow public read-only for verified telemetry"
ON public.esp32_telemetry
FOR SELECT
TO anon, authenticated
USING (integrity_status = 'verified');

-- 7. GRANT FULL PERMISSIONS STRICTLY TO SERVER-SIDE SERVICE ROLE
-- Only the backend ingestion gateway possessing the master service_role key can insert or update
CREATE POLICY "Allow service_role full management"
ON public.esp32_telemetry
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- 8. AUDIT TRIGGER: Guarantee immutable created_at and reject unverified records
CREATE OR REPLACE FUNCTION public.check_telemetry_immutability()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        -- Prevent modification of cryptographic proof fields once recorded
        IF OLD.record_hash IS NOT NULL AND NEW.record_hash <> OLD.record_hash THEN
            RAISE EXCEPTION 'Cryptographic hash cannot be altered on committed telemetry.';
        END IF;
        IF OLD.signature IS NOT NULL AND NEW.signature <> OLD.signature THEN
            RAISE EXCEPTION 'Device signature cannot be altered on committed telemetry.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_protect_telemetry_hashes ON public.esp32_telemetry;
CREATE TRIGGER trg_protect_telemetry_hashes
BEFORE UPDATE ON public.esp32_telemetry
FOR EACH ROW EXECUTE FUNCTION public.check_telemetry_immutability();
